// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC9Pzm3n1OS5K-h6_01B5qlx7JkxSMn9I',
    appId: '1:113393532385:web:448f44dea707e33cb4e6a0',
    messagingSenderId: '113393532385',
    projectId: 'remote-config-demo-eae5f',
    authDomain: 'remote-config-demo-eae5f.firebaseapp.com',
    storageBucket: 'remote-config-demo-eae5f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByDr_R89BY6aelanWTTYPKO_jc7tcEAGI',
    appId: '1:113393532385:android:89923c941d3c0d10b4e6a0',
    messagingSenderId: '113393532385',
    projectId: 'remote-config-demo-eae5f',
    storageBucket: 'remote-config-demo-eae5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbQIbKMEqmiExERT8U1YaPeIu2w2Od7L0',
    appId: '1:113393532385:ios:dcd0b8f190436f92b4e6a0',
    messagingSenderId: '113393532385',
    projectId: 'remote-config-demo-eae5f',
    storageBucket: 'remote-config-demo-eae5f.firebasestorage.app',
    iosBundleId: 'com.example.remoteConfigDemo',
  );
}
